name: Release

on:
  push:
    tags:
    - '*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - id: version
      uses: battila7/get-version-action@v2

    - name: Setup Node
      uses: actions/setup-node@v2.1.0
      with:
        node-version: '12.x'

    - name: Install Dependencies
      run: npm install uglifycss -g

    - name: Build release
      run: |
        uglifycss --ugly-comments --output dist/marcokai.min.css
        cp dist/marcokai.min.css dist/marcokai-${{ steps.version.outputs.version }}.min.css
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add dist
        git commit -m "${{ steps.version.outputs.version }} release"
        git tag ${{ steps.version.outputs.version }}
        git push
